name: Semantic Tag

on:
  push:
    branches: [ 'main' ]

  workflow_dispatch:

jobs:
  tagging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: codfish/semantic-release-action@v2
        with:
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              'next-major',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Get the version
#        id: get_version
#        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Post to Jira webhook
        run: |
          curl -X POST -H 'Content-type: application/json' \
          -d '{"tag":"${{ $RELEASE_VERSION }}"}' \
          https://automation.atlassian.com/pro/hooks/17f087d846e1ffd37f0d5cc19f0d9a0d02507e15

      - run: |
          echo $RELEASE_VERSION
          echo $RELEASE_MAJOR
          echo $RELEASE_MINOR
          echo $RELEASE_PATCH
