name: CI/CD

on:
  pull_request:
    branches:
      - main
      - release
      - develop

  push:
    branches:
      - main
      - release
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - uses: actions/checkout@master

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests
        run: php artisan test

  deploy:
    if: github.event_name == 'push'
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set Forge Webhook
        id: deployment_webhook
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=url::${{ secrets.FORGE_LIVE_DEPLOYMENT_WEBHOOK }}"
          fi
          if [[ "${{github.base_ref}}" == "release" || "${{github.ref}}" == "refs/heads/release" ]]; then
            echo "::set-output name=url::${{ secrets.FORGE_DEMO_DEPLOYMENT_WEBHOOK }}"
          fi
          if [[ "${{github.base_ref}}" == "develop" || "${{github.ref}}" == "refs/heads/develop" ]]; then
            echo "::set-output name=url::${{ secrets.FORGE_TEST_DEPLOYMENT_WEBHOOK }}"
          fi

      - name: Deploy to Forge
        run: curl ${{ steps.deployment_webhook.outputs.url }}

      - name: Move JIRA issues
        if: (github.base_ref == "release" || github.ref == "refs/heads/release")
        run: |
          curl -X POST -H 'Content-type: application/json' \
          https://automation.atlassian.com/pro/hooks/698d80f74701d66b2a9e04e3784d4267d218418f

  automation:
    if: github.event_name == 'push'
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set API url
        id: environment_data
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=environment::${{ secrets.POSTMAN_LIVE_ENVIRONMENT }}"
          fi
          if [[ "${{github.base_ref}}" == "release" || "${{github.ref}}" == "refs/heads/release" ]]; then
            echo "::set-output name=environment::${{ secrets.POSTMAN_DEMO_ENVIRONMENT }}"
          fi
          if [[ "${{github.base_ref}}" == "develop" || "${{github.ref}}" == "refs/heads/develop" ]]; then
            echo "::set-output name=environment::${{ secrets.POSTMAN_TEST_ENVIRONMENT }}"
          fi

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.POSTMAN_APIKEY }}
          collection: ${{ secrets.POSTMAN_COLLECTION_ID }}
          environment: ${{ steps.environment_data.outputs.environment }}
