name: Deploy Workflow

on:
  workflow_run:
    workflows: ["Unit tests"]
    types:
      - completed

  push:
    branches:
      - main
      - 'release/**'
      - develop

jobs:
  call-unit-test-workflow:
    uses: ./.github/workflows/unit_tests.yml

  deploy:
    name: deploy
    needs: [call-unit-test-workflow]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set Forge Webhook
        id: deployment_webhook
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=url::${{ secrets.FORGE_LIVE_DEPLOYMENT_WEBHOOK }}"
          fi
          if [[ "${{github.base_ref}}" == "release" || "${{github.ref}}" == "refs/heads/release" ]]; then
            echo "::set-output name=url::${{ secrets.FORGE_DEMO_DEPLOYMENT_WEBHOOK }}"
          fi
          if [[ "${{github.base_ref}}" == "develop" || "${{github.ref}}" == "refs/heads/develop" ]]; then
            echo "::set-output name=url::${{ secrets.FORGE_TEST_DEPLOYMENT_WEBHOOK }}"
          fi

      - name: Deploy to Forge
        run: curl ${{ steps.deployment_webhook.outputs.url }}

      - name: Set API url
        id: environment_data
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=url::${{ secrets.LIVE_URL }}"
          fi
          if [[ "${{github.base_ref}}" == "release" || "${{github.ref}}" == "refs/heads/release" ]]; then
            echo "::set-output name=url::${{ secrets.DEMO_URL }}"
          fi
          if [[ "${{github.base_ref}}" == "develop" || "${{github.ref}}" == "refs/heads/develop" ]]; then
            echo "::set-output name=url::${{ secrets.TEST_URL }}"
          fi

      - name: Run Newman Collections
        uses: matt-ball/newman-action@master
        with:
          collection: ./tests/newman/postman_collection.json
          delayRequest: 5000
          envVar: '[{ "key": "url", "value": "${{ steps.environment_data.outputs.url }}/api" }]'
