name: Deploy

on:
  workflow_run:
    workflows: ["Unit tests"]
    types:
      - completed

  push:
    branches:
      - main
      - release
      - develop

  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@master

      - name: Set Forge Webhook
        id: deployment_webhook
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=url::${{ secrets.FORGE_LIVE_DEPLOYMENT_WEBHOOK }}"
          fi
          if [[ "${{github.base_ref}}" == "release" || "${{github.ref}}" == "refs/heads/release" ]]; then
            echo "::set-output name=url::${{ secrets.FORGE_DEMO_DEPLOYMENT_WEBHOOK }}"
          fi
          if [[ "${{github.base_ref}}" == "develop" || "${{github.ref}}" == "refs/heads/develop" ]]; then
            echo "::set-output name=url::${{ secrets.FORGE_TEST_DEPLOYMENT_WEBHOOK }}"
          fi

      - name: Deploy to Forge
        run: curl ${{ steps.deployment_webhook.outputs.url }}
