name: Newman Automation

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

  push:
    branches:
      - main
      - release
      - develop

jobs:
  automation:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@master

      - name: Set API url
        id: environment_data
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=environment::${{ secrets.POSTMAN_LIVE_ENVIRONMENT }}"
          fi
          if [[ "${{github.base_ref}}" == "release" || "${{github.ref}}" == "refs/heads/release" ]]; then
            echo "::set-output name=environment::${{ secrets.POSTMAN_DEMO_ENVIRONMENT }}"
          fi
          if [[ "${{github.base_ref}}" == "develop" || "${{github.ref}}" == "refs/heads/develop" ]]; then
            echo "::set-output name=environment::${{ secrets.POSTMAN_TEST_ENVIRONMENT }}"
          fi

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.POSTMAN_APIKEY }}
          collection: ${{ secrets.POSTMAN_COLLECTION_ID }}
          environment: ${{ steps.environment_data.outputs.environment }}
