name: Newman Automation Workflow

on:
  workflow_run:
    workflows: ["Deploy Workflow"]
    types:
      - completed

  push:
    branches:
      - main
      - 'release/**'
      - develop

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set API url
        id: environment_data
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=url::${{ secrets.LIVE_URL }}"
          fi
          if [[ "${{github.base_ref}}" == "release" || "${{github.ref}}" == "refs/heads/release" ]]; then
            echo "::set-output name=url::${{ secrets.DEMO_URL }}"
          fi
          if [[ "${{github.base_ref}}" == "develop" || "${{github.ref}}" == "refs/heads/develop" ]]; then
            echo "::set-output name=url::${{ secrets.TEST_URL }}"
          fi

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.POSTMAN_APIKEY }}
          collection: ${{ secrets.POSTMAN_COLLECTION_ID }}
          environment: ${{ secrets.POSTMAN_TEST_ENVIRONMENT }}
#        id: run-newman
#        uses: anthonyvscode/newman-action@v1
#        with:
#          apiKey: ${{ secrets.POSTMAN_APIKEY }}
#          collection: ${{ secrets.POSTMAN_COLLECTION_ID }}
#          delayRequest: 5000
#          reporters: cli
#
#      - name: Output summary to console
#        run: echo ${{ steps.run-newman.outputs.summary }}
#
#      - name: Output full summary to console
#        run: echo ${{ steps.run-newman.outputs.summary_full }}
